const nodemailer = require('nodemailer')


const getTransporter = () => {
    const transporter = nodemailer.createTransport({
        host: "smtp.mailtrap.io",
        port: 2525,
        auth: {
            user: "33b46591b926b2", //generated by Mailtrap
            pass: "88cd0be2a7c629"  //generated by Mailtrap
        }
    })
    return transporter
}


module.exports = getTransporter